//package com.rickjiang.eatwhat.util;
//
//import com.rickjiang.eatwhat.dao.FoodDao;
//import com.rickjiang.eatwhat.entity.Food;
//
///**
// * Created by 45000 on 2017-07-25.
// */
//
//public class DataBaseUtil {
//    private void addFood() {
//        FoodDao foodDao = new FoodDao(getApplicationContext());
//        String meat = "荤菜";
//        String vegetable = "素菜";
//        String mix = "半荤半素";
//        String soup = "汤";
//
//        Food food = new Food("麻辣香锅",meat);
//        foodDao.add(food);
//        food = new Food("辣椒粉烧排骨",meat);
//        foodDao.add(food);
//        food = new Food("土豆烧鸡腿",meat);
//        foodDao.add(food);
//        food = new Food("啤酒鸭",meat);
//        foodDao.add(food);
//        food = new Food("香辣片片鱼",meat);
//        foodDao.add(food);
//        food = new Food("粉丝蒸虾",meat);
//        foodDao.add(food);
//        food = new Food("萝卜牛腩",meat);
//        foodDao.add(food);
//        food = new Food("红烧鱼",meat);
//        foodDao.add(food);
//        food = new Food("香卤鸡爪",meat);
//        foodDao.add(food);
//        food = new Food("红烧猪蹄",meat);
//        foodDao.add(food);
//        food = new Food("青椒炒肉",meat);
//        foodDao.add(food);
//        food = new Food("酸辣鸡杂",meat);
//        foodDao.add(food);
//        food = new Food("孜然牛肉",meat);
//        foodDao.add(food);
//        food = new Food("蒸蛋饺",meat);
//        foodDao.add(food);
//        food = new Food("黄瓜猪肝",meat);
//        foodDao.add(food);
//        food = new Food("爆炒腰花",meat);
//        foodDao.add(food);
//        food = new Food("蒜苗鸡胸肉",meat);
//        foodDao.add(food);
//        food = new Food("土豆烧鸡",meat);
//        foodDao.add(food);
//        //素菜
//        food = new Food("红烧冬瓜",vegetable);
//        foodDao.add(food);
//        food = new Food("手撕包菜",vegetable);
//        foodDao.add(food);
//        food = new Food("干煸长豆角",vegetable);
//        foodDao.add(food);
//        food = new Food("清炒藕片",vegetable);
//        foodDao.add(food);
//        food = new Food("麻婆豆腐",vegetable);
//        foodDao.add(food);
//        food = new Food("茼蒿菜",vegetable);
//        foodDao.add(food);
//        food = new Food("生菜",vegetable);
//        foodDao.add(food);
//        food = new Food("空心菜",vegetable);
//        foodDao.add(food);
//        food = new Food("红苋菜",vegetable);
//        foodDao.add(food);
//        food = new Food("清炒葫芦瓜",vegetable);
//        foodDao.add(food);
//        food = new Food("肉末茄子",vegetable);
//        foodDao.add(food);
//        food = new Food("西红柿炒蛋",vegetable);
//        foodDao.add(food);
//        food = new Food("酸辣土豆丝",vegetable);
//        foodDao.add(food);
//        food = new Food("小炒杭白菜",vegetable);
//        foodDao.add(food);
//        food = new Food("老南瓜",vegetable);
//        foodDao.add(food);
//        food = new Food("辣椒炒蛋",mix);
//        foodDao.add(food);
//        food = new Food("韭菜炒鸡蛋",mix);
//        foodDao.add(food);
//        food = new Food("肉末酸豆角",mix);
//        foodDao.add(food);
//        food = new Food("蚂蚁上树",mix);
//        foodDao.add(food);
//        food = new Food("茭白炒肉",mix);
//        foodDao.add(food);
//        food = new Food("胡萝卜炒肉",mix);
//        foodDao.add(food);
//        food = new Food("山药炒肉片",mix);
//        foodDao.add(food);
//        food = new Food("莴笋炒肉片",mix);
//        foodDao.add(food);
//        food = new Food("木耳炒肉",mix);
//        foodDao.add(food);
//        food = new Food("蘑菇炒肉",mix);
//        foodDao.add(food);
//        food = new Food("四季豆炒肉",mix);
//        foodDao.add(food);
//        food = new Food("家常煎豆腐",mix);
//        foodDao.add(food);
//        food = new Food("藕片炒肉",mix);
//        foodDao.add(food);
//        food = new Food("黄瓜芹菜炒肉",mix);
//        foodDao.add(food);
//        food = new Food("毛豆炒肉",mix);
//        foodDao.add(food);
//        food = new Food("土豆肉片",mix);
//        foodDao.add(food);
//        food = new Food("肉沫豇豆",mix);
//        foodDao.add(food);
//        food = new Food("香干炒肉",mix);
//        foodDao.add(food);
//        food = new Food("肉片花菜",mix);
//        foodDao.add(food);
//        food = new Food("秋葵炒肉",mix);
//        foodDao.add(food);
//        food = new Food("蘑菇汤",soup);
//        foodDao.add(food);
//        food = new Food("鸡毛菜蛋汤",soup);
//        foodDao.add(food);
//        food = new Food("皮蛋黄瓜汤",soup);
//        foodDao.add(food);
//        food = new Food("苋菜皮蛋汤",soup);
//        foodDao.add(food);
//        food = new Food("海带排骨汤",soup);
//        foodDao.add(food);
//        food = new Food("丝瓜蛋汤",soup);
//        foodDao.add(food);
//        food = new Food("丸子汤",soup);
//        foodDao.add(food);
//        food = new Food("西红柿蛋汤",soup);
//        foodDao.add(food);
//    }
//}
